FROM orthancteam/orthanc:latest

ENV ORTHANC__NAME=PACS-UDLA

ENV ORTHANC__AUTHENTICATION_ENABLED=true

ENV ORTHANC__REGISTERED_USERS={"admin":"admin123"}

ENV ORTHANC__DICOM_WEB__ENABLE=true

ENV ORTHANC__OHIF_ENABLED=true

ENV ORTHANC__OHIF_DATA_SOURCE=dicom-web

EXPOSE 8042
